from .models import Fixture, NewsSignal, Player

PLAYERS: list[Player] = [
    Player(
        id="P1",
        name="Cam Murray",
        team="Rabbitohs",
        positions=["MID"],
        price=760000,
        season_average=61,
        last_3_average=64,
        minutes_adjusted_base=62,
        opponent_modifier=2,
        role_change_modifier=0,
        role_risk=0.12,
        injury_risk=0.08,
        job_security_risk=0.02,
        bye_rounds=[13],
    ),
    Player(
        id="P2",
        name="Reed Mahoney",
        team="Bulldogs",
        positions=["HOK"],
        price=690000,
        season_average=55,
        last_3_average=52,
        minutes_adjusted_base=54,
        opponent_modifier=1,
        role_change_modifier=0,
        role_risk=0.14,
        injury_risk=0.05,
        job_security_risk=0.01,
        bye_rounds=[16],
    ),
    Player(
        id="P3",
        name="Dylan Lucas",
        team="Knights",
        positions=["2RF"],
        price=545000,
        season_average=47,
        last_3_average=58,
        minutes_adjusted_base=53,
        opponent_modifier=2,
        role_change_modifier=3,
        role_risk=0.18,
        injury_risk=0.1,
        job_security_risk=0.08,
        bye_rounds=[16],
    ),
    Player(
        id="P4",
        name="Nicho Hynes",
        team="Sharks",
        positions=["HLF"],
        price=820000,
        season_average=66,
        last_3_average=62,
        minutes_adjusted_base=64,
        opponent_modifier=1,
        role_change_modifier=0,
        role_risk=0.1,
        injury_risk=0.07,
        job_security_risk=0.01,
        bye_rounds=[13],
    ),
    Player(
        id="P5",
        name="Jahream Bula",
        team="Wests Tigers",
        positions=["WFB"],
        price=590000,
        season_average=51,
        last_3_average=56,
        minutes_adjusted_base=54,
        opponent_modifier=2,
        role_change_modifier=1,
        role_risk=0.17,
        injury_risk=0.05,
        job_security_risk=0.07,
        bye_rounds=[13],
    ),
    Player(
        id="P6",
        name="Cheap MID Cashout",
        team="Titans",
        positions=["MID"],
        price=340000,
        season_average=27,
        last_3_average=32,
        minutes_adjusted_base=31,
        opponent_modifier=0,
        role_change_modifier=0,
        role_risk=0.32,
        injury_risk=0.08,
        job_security_risk=0.3,
        bye_rounds=[16],
    ),
    Player(
        id="P7",
        name="Upside Edge",
        team="Raiders",
        positions=["2RF"],
        price=630000,
        season_average=49,
        last_3_average=60,
        minutes_adjusted_base=57,
        opponent_modifier=3,
        role_change_modifier=2,
        role_risk=0.22,
        injury_risk=0.08,
        job_security_risk=0.1,
        bye_rounds=[13],
    ),
    Player(
        id="P8",
        name="Safe Hooker",
        team="Panthers",
        positions=["HOK"],
        price=640000,
        season_average=53,
        last_3_average=54,
        minutes_adjusted_base=52,
        opponent_modifier=1,
        role_change_modifier=0,
        role_risk=0.1,
        injury_risk=0.05,
        job_security_risk=0.03,
        bye_rounds=[13],
    ),
    Player(
        id="P9",
        name="Premium Fullback",
        team="Broncos",
        positions=["WFB"],
        price=810000,
        season_average=64,
        last_3_average=68,
        minutes_adjusted_base=66,
        opponent_modifier=2,
        role_change_modifier=0,
        role_risk=0.11,
        injury_risk=0.06,
        job_security_risk=0.02,
        bye_rounds=[16],
    ),
]

FIXTURES: list[Fixture] = [
    Fixture(round=13, home_team="Rabbitohs", away_team="Sharks"),
    Fixture(round=13, home_team="Bulldogs", away_team="Knights"),
    Fixture(round=13, home_team="Raiders", away_team="Wests Tigers"),
]

NEWS_SIGNALS: list[NewsSignal] = [
    NewsSignal(player_id="P3", signal="named in starting side", confidence="high"),
    NewsSignal(player_id="P6", signal="bench risk", confidence="high"),
    NewsSignal(player_id="P7", signal="role change", confidence="medium"),
]
